### PR TITLE
fix for #18

### PR DESCRIPTION
**Pull request by konstantinzolotarev**
Need to be checked on `node v0.12`

### CODE REVIEW

**Comment by YannBertrand** [comment]
Shouldn't these module be added to the `package.json` dependencies?

**Comment by konstantinzolotarev** [comment]
Basically they are required by `yeoman-generator`.
Tomorrow I'll check on old node versions.

**Comment by jaumard** [comment]
We already fix this on this PR https://github.com/trailsjs/generator-trails/pull/16 :)

**Comment by konstantinzolotarev** [comment]
@jaumard ohh. didn't see this. used search and was not any issues/pr for this.

**Pull request closed without merging**
